# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: pdb_development
  pool: 5
  username: pdb
  password: <%= ENV["PASSWORD_PG"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: pdb_test
  pool: 5
  username: pdb
  password: <%= ENV["PASSWORD_PG"] %>

production:
  <<: *default
  database: db/production.pg
